version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow_server
    restart: always
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow
    volumes:
      - ./mlruns:/mlflow
      - ./mlflow.db:/app/mlflow.db  # Persistent SQLite database for MLflow
